/// LLM-based parser generation agents.
///
/// Implements the "Continuously Evolving" parser zoo from docs/universal_parser.md:
/// - FingerprintGenAgent: analyze log samples → produce fingerprint regex patterns
/// - ParserGenAgent: analyze log samples + fingerprint → produce a parser script
/// - AgentIdGenAgent: analyze log samples → produce agent_id extraction rules
///
/// All agents are iterative: they generate, test, and retry up to max_retries times.
/// They prefer to reuse patterns from existing parsers when possible.
///
/// Why agent_id rules are config (not script): like fingerprints, they're regex-based
/// and benefit from the suggest→user-confirm→store→refine workflow. Keeping them out
/// of the parser script makes them transparent and easy to evolve as new logs arrive.
///
/// Default provider: anthropic/claude-sonnet-4-6
/// For testing: bedrock/us.anthropic.claude-sonnet-4-6
use std::path::{Path, PathBuf};
use std::process::Command;

use regex::Regex;
use serde::Deserialize;

use crate::error::TrajLensError;
use crate::llm::model_registry;
use crate::llm::traits::LLMClient;
use crate::parsing::parser_config::AgentIdRule;

/// Configuration for parser generation agents.
pub struct ParserGenConfig {
    /// LLM model spec ("provider/model-name").
    pub model: String,

    /// Maximum retries for fingerprint/parser generation.
    pub max_retries: usize,

    /// Output directory for configs (e.g. "parsers/configs/").
    pub configs_dir: PathBuf,

    /// Output directory for scripts (e.g. "parsers/scripts/").
    pub scripts_dir: PathBuf,

    /// Optional free-form description of the log batch.
    /// Passed verbatim to all three agents (FingerprintGen, AgentIdGen,
    /// ParserGen) so the LLM can disambiguate domain semantics that aren't
    /// obvious from the log text alone — e.g. "this is a multi-agent
    /// orchestration where each (agent_name) tag in the action header is
    /// an independent worker with its own context window".
    /// None means: no extra context.
    pub batch_description: Option<String>,
}

impl Default for ParserGenConfig {
    fn default() -> Self {
        Self {
            model: "anthropic/claude-sonnet-4-6".to_string(),
            max_retries: 3,
            configs_dir: PathBuf::from("parsers/configs"),
            scripts_dir: PathBuf::from("parsers/scripts"),
            batch_description: None,
        }
    }
}

/// Result of the full parser generation pipeline.
pub struct GeneratedParser {
    /// The log_type_name assigned.
    pub log_type_name: String,

    /// Path to the generated config TOML.
    pub config_path: PathBuf,

    /// Path to the generated parser script.
    pub script_path: PathBuf,

    /// Fingerprint patterns used.
    pub fingerprint: Vec<String>,

    /// Agent_id extraction rules generated by AgentIdGenAgent.
    /// Empty vec means single-agent log (or rules couldn't be derived).
    pub agent_id_rules: Vec<AgentIdRule>,
}

/// Run the full parser generation pipeline:
/// 1. FingerprintGenAgent → fingerprint patterns
/// 2. ParserGenAgent → parser script
/// 3. Validate both against the sample logs
///
/// Returns the generated parser info or an error.
pub async fn generate_parser(
    log_paths: &[PathBuf],
    format_name: &str,
    config: &ParserGenConfig,
) -> Result<GeneratedParser, TrajLensError> {
    if log_paths.is_empty() {
        return Err(TrajLensError::Config("No log files provided".into()));
    }

    // Read sample content (first 200 lines of each log, up to 3 logs)
    let samples = read_samples(log_paths, 200)?;
    let combined_sample = samples.join("\n\n--- NEXT LOG FILE ---\n\n");

    eprintln!("[ParserGen] Creating LLM client: {}", config.model);
    let client = model_registry::create_client(&config.model)
        .await
        .map_err(|e| TrajLensError::Config(format!("LLM client error: {}", e)))?;

    let description = config.batch_description.as_deref();
    if description.is_some() {
        eprintln!("[ParserGen] Using user-provided batch description as additional context.");
    }

    // Step 1: Generate fingerprint
    eprintln!("[ParserGen] Step 1: Generating fingerprint patterns...");
    let fingerprint = generate_fingerprint(
        &*client,
        &combined_sample,
        format_name,
        &samples,
        config.max_retries,
        description,
    )
    .await?;
    eprintln!("[ParserGen] Fingerprint: {:?}", fingerprint);

    // Step 2: Generate agent_id extraction rules.
    // Treated like fingerprints: regex-based, transparent, user-editable.
    // If no markers exist (single-agent log), the agent returns an empty list.
    eprintln!("[ParserGen] Step 2: Generating agent_id extraction rules...");
    let agent_id_rules = generate_agent_id_rules(
        &*client,
        &combined_sample,
        &samples,
        config.max_retries,
        description,
    )
    .await
    .unwrap_or_else(|e| {
        eprintln!(
            "[AgentIdGen] Failed (non-fatal — single-agent log assumed): {}",
            e
        );
        Vec::new()
    });
    if agent_id_rules.is_empty() {
        eprintln!(
            "[ParserGen] No agent_id rules — log is single-agent (or markers undeterminable)."
        );
    } else {
        eprintln!(
            "[ParserGen] {} agent_id rule(s) generated.",
            agent_id_rules.len()
        );
        for r in &agent_id_rules {
            eprintln!("  - {} → {} ({})", r.pattern, r.assign, r.description);
        }
    }

    // Step 3: Generate parser script
    eprintln!("[ParserGen] Step 3: Generating parser script...");
    let script_content = generate_parser_script(
        &*client,
        &combined_sample,
        format_name,
        &fingerprint,
        log_paths,
        config.max_retries,
        description,
    )
    .await?;

    // Step 4: Write outputs
    let config_path = config.configs_dir.join(format!("{}.toml", format_name));
    let script_path = config.scripts_dir.join(format!("{}.py", format_name));

    let config_toml = render_config_toml(format_name, &fingerprint, &agent_id_rules);

    std::fs::write(&config_path, &config_toml)
        .map_err(|e| TrajLensError::Config(format!("Failed to write config: {}", e)))?;
    std::fs::write(&script_path, &script_content)
        .map_err(|e| TrajLensError::Config(format!("Failed to write script: {}", e)))?;

    eprintln!("[ParserGen] Written: {}", config_path.display());
    eprintln!("[ParserGen] Written: {}", script_path.display());

    // Step 5: Validate the generated script runs on the sample
    eprintln!("[ParserGen] Step 4: Validating generated parser...");
    validate_script(&script_path, &log_paths[0])?;
    eprintln!("[ParserGen] Validation passed.");

    Ok(GeneratedParser {
        log_type_name: format_name.to_string(),
        config_path,
        script_path,
        fingerprint,
        agent_id_rules,
    })
}

/// Format the optional batch description as a leading context block for any
/// agent prompt. Empty string when no description was provided so it is a no-op.
fn format_description_block(description: Option<&str>) -> String {
    match description {
        Some(d) if !d.trim().is_empty() => format!(
            "## User-Provided Context\n\n\
             The user has supplied this description of the log batch. Use it to \
             disambiguate the format, identify which agents/sub-agents exist, \
             and recognize domain conventions that aren't obvious from the log \
             text alone:\n\n\
             ---\n{}\n---\n\n",
            d.trim()
        ),
        _ => String::new(),
    }
}

/// Render the parser config as TOML.
///
/// Uses single-quoted TOML literal strings (no escape processing) so regex
/// patterns are stored verbatim. See docs/DEV_NOTES.md for the gotcha.
fn render_config_toml(
    format_name: &str,
    fingerprint: &[String],
    agent_id_rules: &[AgentIdRule],
) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# Auto-generated parser config for {}\n",
        format_name
    ));
    out.push_str(&format!("log_type_name = \"{}\"\n\n", format_name));

    out.push_str("fingerprint = [\n");
    for p in fingerprint {
        out.push_str(&format!("    '{}',\n", p));
    }
    out.push_str("]\n\n");

    out.push_str(&format!("parser = \"{}.py\"\n", format_name));

    if !agent_id_rules.is_empty() {
        out.push_str("\n# Agent_id extraction rules. Applied AFTER the parser script;\n");
        out.push_str("# only steps with agent_id=null are filled. First match wins.\n");
        out.push_str("# Edit freely — these are user-confirmable suggestions from the LLM.\n");
        for rule in agent_id_rules {
            out.push_str("\n[[agent_id_rules]]\n");
            if !rule.description.is_empty() {
                out.push_str(&format!(
                    "description = \"{}\"\n",
                    rule.description.replace('"', "\\\"")
                ));
            }
            out.push_str(&format!("pattern = '{}'\n", rule.pattern));
            out.push_str(&format!("assign = '{}'\n", rule.assign));
        }
    }

    out
}

/// FingerprintGenAgent: generate regex patterns that uniquely identify this log format.
///
/// Requirements:
/// - ALL patterns must match the sample logs
/// - Patterns should be specific enough to not match other formats
/// - 3-5 patterns is ideal
///
/// On failure, feeds error info back to the LLM for correction.
async fn generate_fingerprint(
    client: &dyn LLMClient,
    sample: &str,
    format_name: &str,
    individual_samples: &[String],
    max_retries: usize,
    description: Option<&str>,
) -> Result<Vec<String>, TrajLensError> {
    let system_prompt = FINGERPRINT_SYSTEM_PROMPT;

    let base_message = format!(
        "{}Generate fingerprint regex patterns for a log format named \"{}\".\n\n\
         Log sample (first 200 lines):\n```\n{}\n```\n\n\
         Return ONLY a JSON array of regex pattern strings. Example:\n\
         [\"^\\\\[SYSTEM\\\\]\", \"pattern2\", \"pattern3\"]\n\n\
         Requirements:\n\
         - 3-5 patterns\n\
         - ALL patterns must match ALL provided log files (there are {} files)\n\
         - Each pattern uses standard regex syntax (Rust regex crate, no lookahead)\n\
         - Patterns should capture structural elements unique to this format\n\
         - Only use patterns that appear in EVERY log file, not just some\n",
        format_description_block(description),
        format_name,
        &sample[..sample.len().min(6000)],
        individual_samples.len(),
    );

    let mut user_message = base_message.clone();

    for attempt in 0..max_retries {
        let response = client
            .complete(system_prompt, &user_message)
            .await
            .map_err(|e| TrajLensError::Config(format!("LLM error: {}", e)))?;

        let patterns = extract_json_array(&response);
        if patterns.is_empty() {
            eprintln!(
                "[FingerprintGen] Attempt {}: no patterns extracted, retrying...",
                attempt + 1
            );
            user_message = format!(
                "{}\n\nPREVIOUS ATTEMPT FAILED: Could not parse your response as a JSON array. \
                 Return ONLY a raw JSON array like [\"pat1\", \"pat2\", \"pat3\"]. No markdown.",
                base_message
            );
            continue;
        }

        // Validate: all patterns must match ALL sample logs
        let mut failed_details = Vec::new();
        for (pidx, p) in patterns.iter().enumerate() {
            let re_result = Regex::new(&format!("(?m){}", p));
            match re_result {
                Err(e) => {
                    failed_details.push(format!(
                        "Pattern {} ({:?}) is invalid regex: {}",
                        pidx, p, e
                    ));
                }
                Ok(re) => {
                    for (sidx, s) in individual_samples.iter().enumerate() {
                        if !re.is_match(s) {
                            failed_details.push(format!(
                                "Pattern {} ({:?}) does NOT match log file #{}",
                                pidx,
                                p,
                                sidx + 1
                            ));
                            break;
                        }
                    }
                }
            }
        }

        if failed_details.is_empty() {
            return Ok(patterns);
        }

        eprintln!(
            "[FingerprintGen] Attempt {}: {} issue(s): {}",
            attempt + 1,
            failed_details.len(),
            failed_details.first().unwrap_or(&String::new())
        );

        // Feed failure details back to LLM
        user_message = format!(
            "{}\n\nPREVIOUS ATTEMPT FAILED. Your patterns:\n{}\n\n\
             Issues found:\n{}\n\n\
             Fix: remove or replace the failing patterns. \
             Only use patterns that appear in EVERY log file. \
             Return the corrected JSON array.",
            base_message,
            serde_json::to_string(&patterns).unwrap_or_default(),
            failed_details.join("\n")
        );
    }

    Err(TrajLensError::Config(format!(
        "FingerprintGenAgent failed after {} attempts",
        max_retries
    )))
}

/// AgentIdGenAgent: derive agent_id extraction rules from log samples.
///
/// Returns a list of rules, each with a regex pattern and an `assign` template.
/// An empty list means: this is a single-agent log (no markers found).
///
/// Like fingerprints, these rules are stored in the parser config TOML, so
/// they're transparent and editable by the user. The agent SUGGESTS rules
/// from sample logs; the user can confirm/edit/extend them.
///
/// Validation: each generated regex pattern must compile cleanly.
/// We do NOT validate that rules match the samples — single-agent logs
/// legitimately produce zero rules.
async fn generate_agent_id_rules(
    client: &dyn LLMClient,
    sample: &str,
    individual_samples: &[String],
    max_retries: usize,
    description: Option<&str>,
) -> Result<Vec<AgentIdRule>, TrajLensError> {
    #[derive(Deserialize)]
    struct RuleResponse {
        is_multi_agent: bool,
        rules: Vec<RuleEntry>,
    }
    #[derive(Deserialize)]
    struct RuleEntry {
        #[serde(default)]
        description: String,
        pattern: String,
        assign: String,
    }

    let base_message = format!(
        "{}Analyze the log sample(s) below and decide whether they contain MULTIPLE \
         agent contexts (sub-agents, named workers, parallel jobs).\n\n\
         Log sample:\n```\n{}\n```\n\n\
         Number of log files provided: {}\n\n\
         Return a JSON object:\n\
         {{\n\
           \"is_multi_agent\": true|false,\n\
           \"rules\": [\n\
             {{ \"description\": \"...\", \"pattern\": \"regex with capture groups\", \"assign\": \"$1 or static\" }}\n\
           ]\n\
         }}\n\n\
         If single-agent: set is_multi_agent=false and rules=[]. \
         If multi-agent: provide rules whose `pattern` matches text the parser \
         will see (step content + operation args). Use `$1`, `$2`, ... in `assign` \
         to reference capture groups, or a static string for fixed assignment.\n\n\
         IMPORTANT: do NOT invent boundaries. If markers are not visibly present \
         in the log, return is_multi_agent=false. The downstream LLM patcher will \
         handle implicit boundaries.",
        format_description_block(description),
        &sample[..sample.len().min(6000)],
        individual_samples.len(),
    );

    let mut user_message = base_message.clone();

    for attempt in 0..max_retries {
        let response = client
            .complete(AGENT_ID_SYSTEM_PROMPT, &user_message)
            .await
            .map_err(|e| TrajLensError::Config(format!("LLM error: {}", e)))?;

        // Find the JSON object in the response
        let json_text = extract_json_object(&response);
        if json_text.is_empty() {
            eprintln!(
                "[AgentIdGen] Attempt {}: no JSON object found, retrying...",
                attempt + 1
            );
            user_message = format!(
                "{}\n\nPREVIOUS ATTEMPT FAILED: response was not valid JSON. \
                 Return ONLY a JSON object, nothing else.",
                base_message
            );
            continue;
        }

        let parsed: Result<RuleResponse, _> = serde_json::from_str(&json_text);
        let parsed = match parsed {
            Ok(p) => p,
            Err(e) => {
                eprintln!(
                    "[AgentIdGen] Attempt {}: JSON parse failed: {}",
                    attempt + 1,
                    e
                );
                user_message = format!(
                    "{}\n\nPREVIOUS ATTEMPT FAILED: JSON parse error: {}\n\
                     Return EXACTLY this shape: {{\"is_multi_agent\": bool, \"rules\": [...]}}",
                    base_message, e
                );
                continue;
            }
        };

        // Single-agent → empty rules is the correct answer.
        if !parsed.is_multi_agent {
            return Ok(Vec::new());
        }

        // Validate every regex compiles
        let mut bad = Vec::new();
        for (i, r) in parsed.rules.iter().enumerate() {
            if let Err(e) = Regex::new(&r.pattern) {
                bad.push(format!("rule {} pattern {:?} invalid: {}", i, r.pattern, e));
            }
        }

        if bad.is_empty() {
            return Ok(parsed
                .rules
                .into_iter()
                .map(|r| AgentIdRule {
                    description: r.description,
                    pattern: r.pattern,
                    assign: r.assign,
                })
                .collect());
        }

        eprintln!(
            "[AgentIdGen] Attempt {}: invalid regexes: {:?}",
            attempt + 1,
            bad
        );
        user_message = format!(
            "{}\n\nPREVIOUS ATTEMPT FAILED. Issues:\n{}\n\
             Fix the patterns and return the corrected JSON.",
            base_message,
            bad.join("\n")
        );
    }

    Err(TrajLensError::Config(format!(
        "AgentIdGenAgent failed after {} attempts",
        max_retries
    )))
}

/// Extract a JSON object (curly-braced) from LLM response text.
fn extract_json_object(response: &str) -> String {
    let trimmed = response.trim();
    // Try direct
    if trimmed.starts_with('{') && trimmed.ends_with('}') {
        return trimmed.to_string();
    }
    // Find first { and last }
    if let Some(start) = trimmed.find('{') {
        if let Some(end) = trimmed.rfind('}') {
            if end > start {
                return trimmed[start..=end].to_string();
            }
        }
    }
    String::new()
}

/// ParserGenAgent: generate a Python parser script.
///
/// The script must:
/// - Read log file path from sys.argv[1]
/// - Output Vec<StepInfo> as JSON to stdout
/// - Each StepInfo has: step_id, content, start_time, end_time, metrics, operations[]
async fn generate_parser_script(
    client: &dyn LLMClient,
    sample: &str,
    format_name: &str,
    fingerprint: &[String],
    log_paths: &[PathBuf],
    max_retries: usize,
    description: Option<&str>,
) -> Result<String, TrajLensError> {
    let system_prompt = PARSER_SCRIPT_SYSTEM_PROMPT;

    let user_message = format!(
        "{}Generate a Python parser script for log format \"{}\".\n\n\
         Fingerprint patterns (all match this format):\n{}\n\n\
         Log sample (first 200 lines):\n```\n{}\n```\n\n\
         The script must:\n\
         1. Read log file path from sys.argv[1]\n\
         2. Parse the log into steps\n\
         3. Output JSON array of StepInfo to stdout\n\
         4. StepInfo schema: {{step_id, content, start_time, end_time, metrics, operations[]}}\n\
         5. metrics: {{input_token, output_token, cache_read, cache_write, time, cost, line_range}}\n\
         6. operations[]: [{{type, sub_type, args}}]\n\
         7. Operation types: \"tool\", \"user_input\", \"thinking\", \"event\", \"unknown\"\n\
         8. Wrap uncovered content in <parse_failed>...</parse_failed> tags\n\
         9. line_range MUST be 0-based, end-EXCLUSIVE [start, end). Step N's `end` \
            must equal step N+1's `start` — they MUST NOT overlap (overlapping \
            ranges leak one agent's lines into another's slice).\n\n\
         Return ONLY the Python script (no markdown fences, no explanation).",
        format_description_block(description),
        format_name,
        fingerprint.iter()
            .map(|p| format!("  - {}", p))
            .collect::<Vec<_>>()
            .join("\n"),
        &sample[..sample.len().min(8000)]
    );

    let mut current_user_message = user_message.clone();

    for attempt in 0..max_retries {
        let response = client
            .complete(system_prompt, &current_user_message)
            .await
            .map_err(|e| TrajLensError::Config(format!("LLM error: {}", e)))?;

        let script = extract_python_script(&response);
        if script.is_empty() {
            eprintln!(
                "[ParserGen] Attempt {}: no script extracted, retrying...",
                attempt + 1
            );
            current_user_message = format!(
                "{}\n\nPREVIOUS ATTEMPT FAILED: Could not extract a Python script from your response. \
                 Return ONLY the raw Python code. Do NOT wrap in markdown fences.",
                user_message
            );
            continue;
        }

        // Write to temp file and test
        let tmp_script =
            std::env::temp_dir().join(format!("trajlens_parsergen_{}.py", format_name));
        if let Err(e) = std::fs::write(&tmp_script, &script) {
            eprintln!(
                "[ParserGen] Attempt {}: failed to write temp script: {}",
                attempt + 1,
                e
            );
            continue;
        }

        match test_script(&tmp_script, &log_paths[0]) {
            Ok(result) => {
                if result.warnings.is_empty() {
                    eprintln!(
                        "[ParserGen] Attempt {}: script produced {} steps. OK.",
                        attempt + 1,
                        result.step_count
                    );
                    let _ = std::fs::remove_file(&tmp_script);
                    return Ok(script);
                }
                // Warnings found — feed them back to LLM for correction (unless last attempt)
                if attempt + 1 >= max_retries {
                    eprintln!("[ParserGen] Attempt {}: {} steps with {} warning(s) — accepting (max retries).",
                        attempt + 1, result.step_count, result.warnings.len());
                    let _ = std::fs::remove_file(&tmp_script);
                    return Ok(script);
                }
                eprintln!(
                    "[ParserGen] Attempt {}: {} steps but {} quality warning(s), retrying...",
                    attempt + 1,
                    result.step_count,
                    result.warnings.len()
                );
                let _ = std::fs::remove_file(&tmp_script);
                current_user_message = format!(
                    "{}\n\nPREVIOUS ATTEMPT produced {} steps but has QUALITY ISSUES:\n{}\n\n\
                     Fix these issues in the script. The output MUST:\n\
                     - Have human-readable content (not raw JSON)\n\
                     - Classify every operation with a specific type and sub_type\n\
                     - Fold metadata events into preceding steps' metrics\n\
                     - Extract token counts from the correct nested path\n\
                     Return the corrected script.",
                    user_message,
                    result.step_count,
                    result
                        .warnings
                        .iter()
                        .map(|w| format!("  - {}", w))
                        .collect::<Vec<_>>()
                        .join("\n")
                );
            }
            Err(e) => {
                eprintln!("[ParserGen] Attempt {}: script failed: {}", attempt + 1, e);
                let _ = std::fs::remove_file(&tmp_script);

                // Feed error back for correction
                current_user_message = format!(
                    "{}\n\nPREVIOUS ATTEMPT FAILED when running against the log file.\n\
                     Error: {}\n\n\
                     Fix the script and return the corrected version. \
                     Common issues: missing imports, wrong regex, JSON serialization errors.",
                    user_message, e
                );
            }
        }
    }

    Err(TrajLensError::Config(format!(
        "ParserGenAgent failed after {} attempts",
        max_retries
    )))
}

/// Result of testing a parser script: step count + quality warnings.
struct TestResult {
    step_count: usize,
    warnings: Vec<String>,
}

/// Test a parser script against a log file. Returns step count + warnings.
/// Hard errors (crash, invalid JSON, 0 steps) return Err.
/// Quality issues return Ok with non-empty warnings vec.
fn test_script(script_path: &Path, log_path: &Path) -> Result<TestResult, String> {
    let output = Command::new("python3")
        .arg(script_path)
        .arg(log_path)
        .output()
        .map_err(|e| format!("Failed to execute script: {}", e))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!(
            "Script exited with {}: {}",
            output.status,
            &stderr[..stderr.len().min(500)]
        ));
    }

    let stdout = String::from_utf8_lossy(&output.stdout);
    let steps: Vec<serde_json::Value> =
        serde_json::from_str(&stdout).map_err(|e| format!("Invalid JSON output: {}", e))?;

    if steps.is_empty() {
        return Err("Script produced 0 steps".into());
    }

    // All heuristic checks below are SOFT — they emit warnings but NEVER reject.
    // Warnings are collected and fed back to the LLM for correction on retry.
    let log_text = std::fs::read_to_string(log_path).unwrap_or_default();
    let total_words = log_text.split_whitespace().count();
    let mut warnings: Vec<String> = Vec::new();

    // Heuristic: over-fragmentation (too many tiny steps)
    if total_words > 200 && steps.len() > 1 {
        let words_per_step = total_words / steps.len();
        if words_per_step < 5 {
            warnings.push(format!(
                "OVER-FRAGMENTED: {:.1} words/step average ({} words / {} steps). \
                 Steps may be over-fragmented. Group related lines into logical actions.",
                words_per_step as f64,
                total_words,
                steps.len()
            ));
        }
    }

    // Heuristic: monolithic step (one blob hogging most content)
    if steps.len() >= 2 && total_words > 500 {
        let max_step_words: usize = steps
            .iter()
            .filter_map(|s| s.get("content").and_then(|c| c.as_str()))
            .map(|c| c.split_whitespace().count())
            .max()
            .unwrap_or(0);

        let ratio = max_step_words as f64 / total_words as f64;
        if ratio > 0.8 {
            warnings.push(format!(
                "MONOLITHIC STEP: one step contains {:.0}% of all content \
                 ({} of {} words in {} steps). Split into finer-grained actions.",
                ratio * 100.0,
                max_step_words,
                total_words,
                steps.len()
            ));
        }
    }

    // Heuristic: token metrics all null (extraction path likely wrong)
    let has_token_fields = log_text.contains("token") || log_text.contains("Token");
    if has_token_fields && steps.len() >= 3 {
        let has_any_tokens = steps.iter().any(|s| {
            s.get("metrics")
                .and_then(|m| m.get("input_token"))
                .and_then(|v| v.as_i64())
                .is_some()
        });
        if !has_any_tokens {
            warnings.push(
                "NULL TOKENS: log contains token/cost fields but all steps have null \
                 token metrics. Navigate to the correct nested path (e.g., \
                 payload.tokenUsage.last.inputTokens, not payload.inputTokens)."
                    .into(),
            );
        }
    }

    // Heuristic: raw structured data as content (JSON/YAML dumped verbatim)
    if steps.len() >= 5 {
        let json_content_count = steps
            .iter()
            .filter_map(|s| s.get("content").and_then(|c| c.as_str()))
            .filter(|c| {
                let trimmed = c.trim();
                (trimmed.starts_with('{') && trimmed.contains("\"method\""))
                    || (trimmed.starts_with('{') && trimmed.contains("\"payload\""))
                    || (trimmed.starts_with('[')
                        && trimmed.len() > 200
                        && trimmed.contains("\"type\""))
            })
            .count();
        let ratio = json_content_count as f64 / steps.len() as f64;
        if ratio > 0.3 {
            warnings.push(format!(
                "RAW JSON AS CONTENT: {:.0}% of steps ({}/{}) contain raw JSON/structured data \
                 as content. You MUST interpret structured formats into human-readable text. \
                 Extract the action (command text, agent message, output) from each event. \
                 Never store raw payloads as content — downstream LLM builders cannot use them.",
                ratio * 100.0,
                json_content_count,
                steps.len()
            ));
        }
    }

    // Heuristic: too many "unknown" operations (poor classification)
    if steps.len() >= 5 {
        let unknown_count = steps
            .iter()
            .filter(|s| {
                s.get("operations")
                    .and_then(|ops| ops.as_array())
                    .map(|ops| {
                        ops.iter().all(|op| {
                            let t = op.get("type").and_then(|v| v.as_str()).unwrap_or("unknown");
                            let st = op.get("sub_type").and_then(|v| v.as_str());
                            t == "unknown" || (t != "event" && st.is_none())
                        })
                    })
                    .unwrap_or(true)
            })
            .count();
        let ratio = unknown_count as f64 / steps.len() as f64;
        if ratio > 0.5 {
            warnings.push(format!(
                "UNCLASSIFIED: {:.0}% of steps ({}/{}) have type=unknown or null sub_type. \
                 Classify each step: tool/run for commands, tool/read for file reads, \
                 tool/write for writes, thinking for agent messages, user_input for prompts. \
                 Unknown-typed steps produce empty activity graphs.",
                ratio * 100.0,
                unknown_count,
                steps.len()
            ));
        }
    }

    // Heuristic: metadata events as standalone steps
    if steps.len() >= 10 {
        let metadata_patterns = [
            "token",
            "rate_limit",
            "rateLimits",
            "status/changed",
            "settings/updated",
            "remoteControl",
        ];
        let metadata_step_count = steps
            .iter()
            .filter(|s| {
                let content = s.get("content").and_then(|c| c.as_str()).unwrap_or("");
                let ops = s.get("operations").and_then(|o| o.as_array());
                let is_event_type = ops
                    .map(|arr| {
                        arr.iter().any(|op| {
                            let t = op.get("type").and_then(|v| v.as_str()).unwrap_or("");
                            t == "event"
                        })
                    })
                    .unwrap_or(false);
                is_event_type && metadata_patterns.iter().any(|p| content.contains(p))
            })
            .count();
        let ratio = metadata_step_count as f64 / steps.len() as f64;
        if ratio > 0.2 {
            warnings.push(format!(
                "METADATA AS STEPS: {:.0}% of steps ({}/{}) are metadata events \
                 (token usage, rate limits, status). Fold these into the preceding \
                 action step's metrics instead of emitting as standalone steps.",
                ratio * 100.0,
                metadata_step_count,
                steps.len()
            ));
        }
    }

    for w in &warnings {
        eprintln!("  ⚠ [ParserGen] {}", w);
    }

    Ok(TestResult {
        step_count: steps.len(),
        warnings,
    })
}

/// Validate a script runs and produces valid output.
fn validate_script(script_path: &Path, log_path: &Path) -> Result<(), TrajLensError> {
    match test_script(script_path, log_path) {
        Ok(result) if result.step_count > 0 => Ok(()),
        Ok(_) => Err(TrajLensError::Config("Parser produced 0 steps".into())),
        Err(e) => Err(TrajLensError::Config(format!(
            "Parser validation failed: {}",
            e
        ))),
    }
}

/// Read first N lines from up to 3 log paths (files or directories).
///
/// For directories: reads representative files from within the tree.
fn read_samples(paths: &[PathBuf], max_lines: usize) -> Result<Vec<String>, TrajLensError> {
    let mut samples = Vec::new();
    for path in paths.iter().take(3) {
        if path.is_dir() {
            let dir_sample = read_dir_sample(path, max_lines)?;
            if !dir_sample.is_empty() {
                samples.push(dir_sample);
            }
        } else {
            let content = std::fs::read_to_string(path).map_err(|e| {
                TrajLensError::Config(format!("Failed to read {}: {}", path.display(), e))
            })?;
            let lines: Vec<&str> = content.lines().take(max_lines).collect();
            samples.push(lines.join("\n"));
        }
    }
    Ok(samples)
}

/// Read representative samples from a directory tree.
fn read_dir_sample(dir: &Path, max_lines: usize) -> Result<String, TrajLensError> {
    let mut parts = Vec::new();
    let mut visited = 0;

    fn walk(dir: &Path, parts: &mut Vec<String>, visited: &mut usize, max_lines: usize) {
        if *visited >= 5 {
            return;
        }
        let entries = match std::fs::read_dir(dir) {
            Ok(e) => e,
            Err(_) => return,
        };
        let mut entries: Vec<_> = entries.flatten().collect();
        entries.sort_by_key(|e| e.file_name());
        for entry in entries {
            if *visited >= 5 {
                break;
            }
            let path = entry.path();
            if path.is_dir() {
                walk(&path, parts, visited, max_lines);
            } else {
                let ext = path.extension().and_then(|s| s.to_str()).unwrap_or("");
                if matches!(ext, "json" | "log" | "yaml" | "yml" | "jsonl" | "txt") {
                    if let Ok(content) = std::fs::read_to_string(&path) {
                        let head: String = content
                            .lines()
                            .take(max_lines)
                            .collect::<Vec<_>>()
                            .join("\n");
                        parts.push(format!("=== {} ===\n{}", path.display(), head));
                        *visited += 1;
                    }
                }
            }
        }
    }

    walk(dir, &mut parts, &mut visited, max_lines);
    Ok(parts.join("\n\n--- NEXT FILE ---\n\n"))
}

/// Extract a JSON array from LLM response text.
fn extract_json_array(response: &str) -> Vec<String> {
    // Try to find a JSON array in the response
    let trimmed = response.trim();

    // Try direct parse
    if let Ok(arr) = serde_json::from_str::<Vec<String>>(trimmed) {
        return arr;
    }

    // Try extracting from markdown code block
    if let Some(start) = trimmed.find('[') {
        if let Some(end) = trimmed.rfind(']') {
            let slice = &trimmed[start..=end];
            if let Ok(arr) = serde_json::from_str::<Vec<String>>(slice) {
                return arr;
            }
        }
    }

    Vec::new()
}

/// Extract Python script from LLM response.
fn extract_python_script(response: &str) -> String {
    let trimmed = response.trim();

    // If wrapped in ```python ... ```
    if let Some(start) = trimmed.find("```python") {
        let content_start = start + 9;
        let content_start = if trimmed[content_start..].starts_with('\n') {
            content_start + 1
        } else {
            content_start
        };
        if let Some(end_offset) = trimmed[content_start..].find("```") {
            return trimmed[content_start..content_start + end_offset]
                .trim()
                .to_string();
        }
    }

    // If wrapped in ``` ... ```
    if let Some(start) = trimmed.find("```") {
        let content_start = start + 3;
        let content_start = if trimmed[content_start..].starts_with('\n') {
            content_start + 1
        } else {
            content_start
        };
        if let Some(end_offset) = trimmed[content_start..].find("```") {
            let content = &trimmed[content_start..content_start + end_offset];
            if content.contains("import") || content.contains("def ") {
                return content.trim().to_string();
            }
        }
    }

    // If it starts with import/"""/#!, treat as raw script
    if trimmed.starts_with("import ")
        || trimmed.starts_with("\"\"\"")
        || trimmed.starts_with("#!/")
        || trimmed.starts_with("from ")
    {
        return trimmed.to_string();
    }

    String::new()
}

// ============ System Prompts ============

const FINGERPRINT_SYSTEM_PROMPT: &str = r#"You are a log format fingerprint generator for TrajLens.

Your task: given a sample of a log file, produce 3-5 regex patterns that UNIQUELY identify this log format. ALL patterns must match the sample.

Rules:
- Return ONLY a JSON array of regex strings. No explanation.
- Patterns use standard regex (Rust regex crate compatible).
- Each pattern should match at least once in the log sample (multiline mode is enabled, ^ matches line starts).
- Prefer structural markers: timestamps formats, module names in brackets, sentinel lines, unique keywords.
- Avoid overly generic patterns (e.g. "\d+" alone is too broad).
- Escape special regex characters properly (dots, brackets, etc.).
- Do NOT use lookahead/lookbehind (not supported).
- If a directory contains multiple file types (e.g., trajectory JSONs + metadata JSONs),
  the fingerprint must ONLY match files that contain actual trajectory data. Test that
  auxiliary files (metadata, config, summaries) do NOT match all patterns.
- If the sample appears to be a fragment of a larger format (same structural markers
  but missing global elements like summaries), note that the fingerprint should target
  the COMPLETE format, not fragments.

Example output:
["^\\[SYSTEM\\]", "\\[cyberagent\\.orchestrator\\]", "Score:\\s*\\d+\\s*\\|\\s*RCE="]
"#;

const AGENT_ID_SYSTEM_PROMPT: &str = r#"You are an agent_id rule extractor for TrajLens.

A log may contain steps from multiple agents whose context windows are independent:
- A main agent that spawns sub-agents (e.g. Claude Code's Task tool)
- A multi-agent system with named workers (e.g. jobA/jobB, pi-GPT5.5/codex-GPT5.5)
- Iterative orchestration with named iterations
- Action-tagged trajectories (e.g. each step prefixed with (agent_name))

YOUR JOB: detect such markers in the log sample and return regex extraction rules.

WHEN TO EMIT RULES (is_multi_agent=true):
You see TWO OR MORE distinct agent names appearing on different steps.
The names appear in a CONSISTENT, REGEX-EXPRESSIBLE position (a tag, prefix,
field, or annotation that recurs across steps).

Concrete signals (any one is enough):
- Multiple distinct names in `worker:` / `agent:` / `agent_id:` fields
- Distinct prefixes like `[worker_a]`, `[worker_b]`, `[sub1]`, `[sub2]`
- Action lines tagged with parenthesized agent names like `(file_access) >>>`,
  `(rce) >>>`, `(db_mod) >>>` — IF you see ≥2 distinct names, this IS multi-agent
- Distinct named blocks like `===== AGENT FOO =====` ... `===== AGENT BAR =====`

Count the distinct names you see. If ≥2, EMIT RULES — do not be conservative.
The signal is the visible recurring pattern, not your judgment about whether
the agents "really" have separate contexts. That's the user's call to confirm.

WHEN NOT TO EMIT (is_multi_agent=false):
- Only one agent name appears (single-agent log).
- Boundaries are narrative-only ("Now I'll spawn a sub-agent...") with no
  recurring tag. Leave for the LLM patcher.

A "rule" has:
- pattern: a Rust-compatible regex tested against each step's text
- assign: an agent_id template; use $1, $2, ... for capture groups, or a
  static string for fixed assignment
- description: a short human-readable explanation

EXAMPLES:

Sample shows: `[1] (file_access) >>> Bash ...` and `[2] (rce) >>> Bash ...`
Correct response (multi-agent — at least 2 distinct names: file_access, rce):
{ "is_multi_agent": true, "rules": [
  { "description": "Action-tagged agent name in parentheses",
    "pattern": "\\((file_access|rce|db_mod|db_read|file_creation|data_exfil|auth_bypass|post_rce)\\)\\s*>>>",
    "assign": "$1" }
] }

Sample shows: `worker: pi-GPT5.5` and `worker: codex-GPT5.5`
Correct response:
{ "is_multi_agent": true, "rules": [
  { "description": "Worker name in metadata",
    "pattern": "worker:\\s*(\\S+)", "assign": "$1" }
] }

Sample shows: just one agent throughout
Correct response: { "is_multi_agent": false, "rules": [] }

Output JSON shape (no markdown, no explanation):
{
  "is_multi_agent": true|false,
  "rules": [ { "description": "...", "pattern": "...", "assign": "..." }, ... ]
}

Rules are evaluated in order; first match wins. Put more specific rules first.
Prefer ONE rule with alternation `(a|b|c)` over multiple separate rules.
"#;

const PARSER_SCRIPT_SYSTEM_PROMPT: &str = r#"You are a log parser script generator for TrajLens.

Your task: generate a complete, working Python script that parses an AI agent's execution log into structured steps representing its TRAJECTORY (sequence of actions and decisions).

# CRITICAL: What is a "step"?

A step is ONE MEANINGFUL AGENT ACTION CYCLE — NOT a log line. Think of it as:
- One LLM call + its tool executions and results
- One iteration of an agent loop
- One request-response cycle (e.g., one audit validation with INPUT → reasoning → OUTPUT)
- One phase transition or significant decision point

A 1000-line log should typically produce 5-50 steps, NOT 1000 steps.
Individual log lines are NOT steps. They are fragments WITHIN a step.

How to identify step boundaries:
- Look for INDIVIDUAL TOOL CALLS — each tool invocation (bash, read, write, submit,
  execute, etc.) is typically one step. This is the PRIMARY boundary.
- Look for request/response pairs (INPUT START → OUTPUT END)
- Look for phase changes (Phase 1 → Phase 2)
- Look for tool call + result pairs ([TOOL] → [SUCCESS])
- Group consecutive log lines that belong to the same logical action

IMPORTANT TRAP TO AVOID: "iteration" or "loop" markers are NOT always the right
step boundary. In some agent frameworks, a single "Iteration 0" contains HUNDREDS
of tool calls in an inner loop. If you split only on iteration headers, you'll get
one monolithic 5000-line step containing 300 tool calls — that defeats the purpose.
Always check if there are finer-grained action boundaries INSIDE what looks like
a high-level delimiter. Prefer: THE SMALLEST MEANINGFUL ACTION IS THE STEP.
NOTE: this is a soft guideline, not a hard rule. Rare legitimate cases exist (e.g.,
a single enormous LLM output that IS one logical step). If in doubt, prefer
finer granularity — the downstream system can always group steps, but cannot split
a monolithic blob after the fact.

# CRITICAL: What to DROP

We only care about the agent's TRAJECTORY — its actions, decisions, and reasoning.
Mark irrelevant noise with <dropped> tags so downstream won't see it.
Content to drop (do NOT include as steps or content):
- HTTP access logs / probe requests (GET /foo 404, etc.) — these are external noise, not agent actions
- Low-level library debug logs (botocore, httpcore, SSL handshake, connection pooling)
- Repeated identical lines (keep only the first occurrence or a count summary)
- Infrastructure noise (health checks, heartbeats, metric exports)
- Stack traces from non-critical warnings

The <dropped> tag works like <parse_failed>: wrap dropped content so it's excluded from analysis.
Example: if 500 lines are HTTP probes between two real steps, drop them entirely — do not create a step for them.

# What to KEEP as steps

- Agent receiving a task / request
- Agent reasoning or planning
- Agent calling tools (LLM calls, file reads, command execution)
- Agent producing results / verdicts / outputs
- Phase transitions, retries, error recovery
- Final outcome / summary

# agent_id

agent_id (which agent owns each step) is handled by SEPARATE config rules,
not by your script. Your script can simply leave agent_id=null on every step.
A separate AgentIdGenAgent generates regex rules that are stored in the parser
config TOML and applied AFTER your script runs.

You only need to handle agent_id yourself if there's something the regex rules
genuinely cannot express (extremely rare). In that case, set agent_id explicitly
in your output and the config rules will skip those steps.

# Output Schema

The script MUST:
1. Be a standalone Python file (no external dependencies beyond stdlib + json + re)
2. Read the log file path from sys.argv[1]
3. Output a JSON array to stdout
4. Each element is a StepInfo dict with these fields:
   - step_id: int (sequential)
   - agent_id: str or null (which agent owns this step — see "agent_id" rules above)
   - content: str — HUMAN-READABLE text describing what happened in this step.
     For structured formats (JSON, YAML, etc.), you MUST INTERPRET the data and
     produce readable text. NEVER store raw JSON/YAML/XML as content.
     Good: "[COMMAND] find src/ -name *.py\n[OUTPUT] found 3 files..."
     Good: "[AGENT] I'll try a different approach using SQL injection..."
     Bad:  '{"method": "item/completed", "payload": {"item": ...}}'
     Bad:  raw serialized objects or data structures
     The content field is consumed by LLM-based graph builders (G1, G2) — if you
     feed them raw JSON, they produce garbage. INTERPRET the structured data into
     natural-language-like descriptions of agent actions.
   - start_time: str or null (ISO datetime like "2026-04-08 03:53:39")
   - end_time: str or null
   - metrics: dict with keys: input_token, output_token, cache_read, cache_write, time, cost, line_range
       - line_range: [start, end] in the ORIGINAL log file using
         **0-based indexing, end-EXCLUSIVE** (Python slice convention).
         If step content is at lines[i] through lines[j-1], emit [i, j].
         Step N's `end` should equal step N+1's `start` — they must NOT overlap.
         This is critical: in multi-agent logs, overlapping ranges leak one
         agent's lines into another's slice.
       - Token metrics: if the format has token counts in a nested structure
         (e.g., payload.tokenUsage.last.inputTokens), you MUST navigate to
         the actual leaf values. The validator checks for this.
   - operations: list of dicts, each with: type (str), sub_type (str or null), args (list of str)
5. Operation types: "tool", "user_input", "thinking", "event", "unknown"
   - "tool" with sub_type: the specific tool name ("run", "read", "write", "search", "submit")
   - "thinking" with sub_type: reasoning/planning step
   - "user_input": user or system prompt to the agent
   - "event": a significant event (phase change, outcome, etc.)
   - "unknown" ONLY as a last resort — if you can determine the action type, do so.
   Every step MUST have sub_type set when the data indicates what kind of action it is.
   The downstream graph builders use operation types for categorization — "unknown"
   with null sub_type produces empty graphs.
6. Any content the parser cannot classify must be wrapped in <parse_failed>...</parse_failed> tags
7. Noise/irrelevant content must be excluded entirely (not emitted as steps)

# Rules

- Output ONLY the Python script. No markdown fences, no explanation text.
- The script must handle edge cases gracefully (empty files, malformed lines).
- Prefer simple, robust parsing over complex regex.
- Use the log structure evident from the sample (timestamps, delimiters, blocks).
- The script must produce at least 1 step for any non-empty log file.
- A step groups multiple related log lines into ONE coherent unit of work.
- Use datetime.fromtimestamp(ts, tz=datetime.timezone.utc) NOT datetime.utcfromtimestamp(ts)
  (the latter is deprecated in Python 3.12+).
- Every step MUST have at least one classified operation. Do not leave sub_type as None
  when the data clearly indicates what kind of action occurred. Map event types to
  operation sub_types: commandExecution→"run", agentMessage→"thinking",
  userMessage→"user_input", submit→"submit", search→"search".
- Do NOT create one step per log line. That defeats the purpose of parsing.
- Do NOT create steps for HTTP access logs, debug noise, or infrastructure chatter.
- Focus on the agent's decision-making trajectory: what did it do, and what happened?

# Operational metadata — NOT steps

These events carry information but are NOT agent actions. NEVER emit them as steps:
- Token usage updates (thread/tokenUsage/updated, cost summaries)
- Rate limit notices
- Status changes (thread/status/changed, connection state)
- Heartbeats, keep-alives, internal framework bookkeeping

Instead: FOLD their data into the PRECEDING action step's `metrics` fields.
For example, if a token-usage event follows a command execution:
  - The command execution is the step
  - The token usage data goes into that step's metrics.input_token, metrics.output_token

The VALIDATION will count steps that have type="event" with sub_types matching
metadata patterns. If >30% of steps are metadata events, the parser is broken.

# Outcome detection

If the log contains an explicit success/failure indicator for the overall trajectory:
- A "SOLVED" / "SUCCESS" / "PASSED" marker
- A structured field like {"success": true, "verified": true}
- A "Result: FAIL" or "FAILED" line

Then the LAST step should be an operation of type="event", sub_type="outcome" with
args=["success"] or args=["failure"]. This lets the framework set the trajectory
outcome (SOLVED/FAILED) without LLM inference.

# Folder-based logs

The input path (sys.argv[1]) may be a DIRECTORY instead of a single file.
Some agent frameworks produce multi-file logs in a folder structure:
- Multiple JSON files per agent/vector/attempt (e.g., exploit_rce_a1.json, analysis_rce_a1.json)
- Subdirectories like logs/ and trajectories/
- A request.json or metadata file alongside the actual trajectory files

When the input is a directory:
1. Walk the directory tree and collect all parseable files
2. Determine which files contain actual trajectory data vs. metadata/config
3. Parse each trajectory file and combine steps, ordered by timestamp
4. Set agent_id based on filename or directory structure when possible
5. Use os.path.isdir() to detect directory input

When the input is a single file, parse it as before.

# CRITICAL: The parser must NEVER refuse to parse a log.

Heuristic rules (step granularity, noise filtering, etc.) are SOFT guidelines.
The parser must ALWAYS produce output for ANY valid input, even if the result is
imperfect. If a heuristic would cause the parser to produce zero steps or crash,
SKIP that heuristic and fall back to a coarser-grained parse.

Example: if no tool-call markers are found, fall back to iteration-level splitting.
If no iteration markers either, treat the whole log as one step. Never sys.exit(1)
or raise an exception because a log doesn't fit the expected pattern — degrade
gracefully and let the downstream LLM patcher handle the imperfection.
"#;
